Support looping plugins

diff --git a/functions/plugin-load b/functions/plugin-load
--- a/functions/plugin-load
+++ b/functions/plugin-load
@@ -1,15 +1,17 @@
 #!/bin/zsh
 #function plugin-load {
   : ${REPO_HOME:=${XDG_CACHE_HOME:-$HOME/.cache}/repos}
-  local plugin=$1
-  local inits=(
-    {$ZSH_CUSTOM,$ZSH}/plugins/$plugin/${plugin}.plugin.zsh(N)
-    $REPO_HOME/$plugin/${plugin:t}.plugin.zsh(N)
-    $REPO_HOME/$plugin/*.{plugin.zsh,zsh,zsh-theme}(N)
-  )
-  if ! (( $#inits )); then
-    echo >&2 "plugin-load: Plugin not found '$1'."
-    return 1
-  fi
-  source $inits[1]
+  local plugin inits=()
+  for plugin in $@; do
+    inits=(
+      {$ZSH_CUSTOM,$ZSH}/plugins/$plugin/${plugin}.plugin.zsh(N)
+      $REPO_HOME/$plugin/${plugin:t}.plugin.zsh(N)
+      $REPO_HOME/$plugin/*.{plugin.zsh,zsh,zsh-theme}(N)
+    )
+    if ! (( $#inits )); then
+      echo >&2 "plugin-load: Plugin not found '$1'."
+      continue
+    fi
+    source $inits[1]
+  done
 #}
